### ISSUE TITLE
add Europeana dataset for detecting concepts

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/CKEditor-Plugin#23]
The name of the dataset for NER is `europeana`.

**Comment by bjdmeest** [comment]
fixed by 18be046b80819add663da529c46518ebff65cfef

I only merged to the dev-branch, because this dataset isn't available yet in any release. Will update the master branch once europeana is added to a release to (should I make an extra issue for this? I assume europeana will be added in the future 0.8(?) release?)

**Comment by pheyvaer** [comment]
@m1ci do you know this?

**Comment by m1ci** [comment]
Europeana is only available via the dev API. Should we add it to the live API as well?
Adding @jnehring and @sandroacoelho in the loop.

**Comment by pheyvaer** [comment]
I think so yes.

**Comment by sandroacoelho** [comment]
Hi @m1ci , @pheyvaer,

I have a dump of Europeana. Until Wednesday I will make available in freme-live.

**Comment by sandroacoelho** [comment]
Hi @pheyvaer @m1ci 

Europeana dump is available under [/dev/europeana](https://www.dropbox.com/sh/xvhf1igrvldw5ni/AAA9aYDzJwXYUlSV2JYpWBMta?dl=0) and in [SOLR LIVE](http://rv2622.1blu.de/solrlive/elinker/select?q=dataset%3Aeuropeana&wt=json&indent=true) as promised

Best,

**Comment by bjdmeest** [comment]
fixed by a8356af5d3cece980b22c2bf03434553105f9586
