### ISSUE TITLE
Missing templates

### ISSUE THREAD

**Issue by jnehring** [freme-project/CKEditor-Plugin#32]
"Fetch additional information" does not work because of missing e-link templates. Hopefully this will be fixed by https://github.com/freme-project/freme-parent/issues/4

**Comment by jnehring** [comment]
The templates where added but the CKEditor plugin still does not work because the template id has changed. @pheyvaer has released a new version of the CKEditor plugin which uses the new ID of the template from the ADAPT server. It is available at the rv1460.1blu.de server.

@munnellg please copy the folder /var/www/html/ckeditor from the rv1460.1blu.de server and replace the ADAPT CKEditor plugin installation with this folder.

**Comment by munnellg** [comment]
@jnehring I've replaced the CKEditor, but I'm not sure how to test if it works

However, I have noticed that the e-link option for the freme-workflow-editor suffers from an error due to the templates as well. It is looking for a template with id 4476. I think this is easy enough to change on my end by modifying /var/www/html/freme-workflow-editor/assets/html/elink.html, but I just want to confirm before I start making changes

**Comment by jnehring** [comment]
I checked https://api.freme-project.eu/ckeditor/ckeditor/samples/freme.html and the issue is solved. The bug you discovered is exactly what we changed so you do not need to update anything.
